# Jinja template: Process setup.py to obtain version and metadata
{% set data = load_setup_py_data() %}

package:
  name: pipemake_utils
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: "Pipemake Utilities"

build:
  number: 0
  entry_points:
    - process-braker=pipemake_utils.process_braker:main
    - ped-phenotype-file=pipemake_utils.ped_phenotype_file:main
    - model-inds=pipemake_utils.model_inds:main
    - filter-gemma=pipemake_utils.filter_gemma:main
    - model-pop-files=pipemake_utils.model_pop_files:main
    - plot-pca=pipemake_utils.plot_pca:main
    - manhattan-plot=pipemake_utils.manhattan_plot:main
    - z-normalize=pipemake_utils.z_normalize:main
    - featureCounts-report=pipemake_utils.featureCounts_report:main
    - softmask=pipemake_utils.softmask:main
    - longest-transcript=pipemake_utils.longest_transcript:main
    - add-eggnog-annotations=pipemake_utils.add_eggnog_annotations:main

source:
  path: ../../

requirements:
  host:
    - pip
    - python >=3.8,<=3.12
    - conda-forge/label/python_rc::_python_rc
  run:
    - pip
    - python >=3.8,<=3.12
    - conda-forge::python_abi <=3.12
    - bioconda::gffutils >=0.13
    - conda-forge::biopython >=1.84
    - conda-forge::seaborn >=0.13.2
    - conda-forge::pandas >=2.2.3
    - conda-forge::numpy >=2.1.3
    - conda-forge::scipy >=1.14.1
    - conda-forge::pyyaml >=6.0.2

test:
  imports:
    - pipemake_utils
  run:
    - add-eggnog-annotations --help
