# Jinja template: Process setup.py to obtain version and metadata
{% set data = load_setup_py_data() %}

package:
  name: pipemake
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: "Pipemake Utilities"

build:
  number: 0
  entry_points:
    - pipemake=pipemake.pipemake:main

source:
  path: ../../

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pip
    - python >=3.8
    - bioconda::gffutils >=0.13
    - conda-forge::biopython >=1.84
    - conda-forge::seaborn >=0.13.2
    - conda-forge::pandas >=2.2.3
    - conda-forge::numpy >=2.1.3
    - conda-forge::scipy >=1.14.1

test:
  imports:
    - pipemake_utils
  run:
    - add-eggnog-annotations --help
