name: Conda Upload

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          activate-environment: pipemake_utils
          environment-file: .conda/environment_build.yml
          python-version: 3.9
          channels: conda-forge,bioconda,conda-forge/label/python_rc
          channel-priority: true
      - name: Build MacOS - External
        if: matrix.os == 'macos-latest'
        shell: powershell
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          conda build .conda/pipemake_utils --output-folder build
          anaconda -t "$env:ANACONDA_API_TOKEN" upload --user kocherlab build/osx-arm64/*.conda
        
